#!/usr/local/bin/python
import sys
import os

args = sys.argv[1:]
if args:
  files = ""
  for i in args:
    if not i.endswith(".tex"):
      i += ".tex"
    files += i + " "
  os.system("pdflatex " + files)
else:
  os.system("pdflatex *.tex")
