"""
YOU SHOULD MODIFY THE FOLLOWING ITEMS AND 
SAVE THE FILE AS `settings.py`.
"""

# your absolute path of this file directory
abspath = "/your/abs/path/to/createx/"

# author name you wanted to include in the templates
author = "Your Name"

# date you want to use in the templates
date = r"\today"

# left headers you want to use
headerL = "LEFT TOP HEADER"

# right headers you want to use
headerR = r"\today"

# footer you want to include
footer = "generated by \emph{createx}"

# the theme when generating beamer
# see https://latex-beamer.com/tutorials/beamer-themes/ for more information
beamertheme = "Singapore"

