# your absolute path of this file directory
abspath = "/Users/liujingyu/createx/"

# author name you wanted to include in the templates
author = "Liu Jingyu"

# date you want to use in the templates
date = r"\today"

# left headers you want to use
headerL = "LIU JINGYU"

# right headers you want to use
headerR = r"\today"

# footer you want to include
footer = "GENERATED BY CREATEX"

# the theme when generating beamer
# see https://latex-beamer.com/tutorials/beamer-themes/ for more information
beamertheme = "Boadilla"
